# Generated by Django 5.0.1 on 2024-02-03 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='HistoryView',
        ),
        migrations.RenameModel(
            old_name='WatchList',
            new_name='WatchListView',
        ),
        migrations.CreateModel(
            name='PreferedGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('search_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prefered_genre',
                'verbose_name_plural': 'prefered_genres',
                'db_table': 'prefered_genre',
            },
        ),
    ]
